name: Validate Android

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/validate-android.yml'
      - 'packages/react-native-quick-crypto/android/**'
      - '.editorconfig'
  pull_request:
    paths:
      - '.github/workflows/validate-android.yml'
      - 'packages/react-native-quick-crypto/android/**'
      - '.editorconfig'

jobs:
  validate_android:
    name: Gradle Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 22
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: false
          # this cmdline tools version barked the least in GHA runners
          # hopefully we can remove it in the future
          cmdline-tools-version: 9477386

      - name: Bootstrap JS
        run: |
          bun install

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Gradle Lint
        run: cd example/android && ./gradlew lint

      - name: Parse Gradle Lint Report
        uses: yutailang0119/action-android-lint@v4
        with:
          # ignore-warnings: true
          report-path: example/android/app/build/reports/*.xml
