name: Validate Android

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/validate-android.yml'
      - 'packages/react-native-quick-crypto/android/**'
      - '.editorconfig'
  pull_request:
    paths:
      - '.github/workflows/validate-android.yml'
      - 'packages/react-native-quick-crypto/android/**'
      - '.editorconfig'

jobs:
  validate_android:
    name: Gradle Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 22

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: false
          # this cmdline tools version barked the least in GHA runners
          # hopefully we can remove it in the future
          cmdline-tools-version: 9477386

      - name: Restore Gradle cache
        uses: actions/cache/restore@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle

      - name: Bootstrap JS
        run: |
          bun install

      - name: Run Gradle Lint
        # Lint only our module with single arch - C++ build is required but lint only checks Java/Kotlin
        run: cd example/android && ./gradlew :react-native-quick-crypto:lintDebug -PreactNativeArchitectures=x86_64

      - name: Parse Gradle Lint Report
        uses: yutailang0119/action-android-lint@v4
        with:
          # ignore-warnings: true
          report-path: example/node_modules/react-native-quick-crypto/android/build/reports/lint-results-debug.xml

      - name: Save Gradle cache
        if: always()
        uses: actions/cache/save@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle
